name: Update DNP Cache
on:
  workflow_dispatch:
  schedule:
  - cron: "21 * * * *"

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'
    - run: npm ci
    - run: npm run fetch